db:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
  volumes:
    - ./:/var/lib/mysql
